### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by kaarigar** [HemulGM/DALL-E#2]
I am compiling in Delphi 11.3 for Win64 target and I get following error. I have installed latest HGMComponents from the repository. Any help is appreciated! Thanks!

`[dcc64 Error] DALLE.FrameImage.pas(48): E2250 There is no overloaded version of 'LoadFromUrlAsync' that can be called with these arguments`

**Comment by HemulGM** [comment]
Not actual project. DALL-E built into the ChatGPT client.

**Comment by kaarigar** [comment]
Ok, got it.
